# This file is wildly permissive, because codecov.io fails the build too often, and for reasons we do not agree with.
# So this file allows us to use the codecov.io UI without dealing with their poor logic for failing the build.
coverage:
  status:
    project:
      default:
        target: 90%     # the required coverage value: 90%
        threshold: 99%  # allows a 99% drop from the previous base commit coverage
    patch:
      default:
        informational: true  # set non-blocking status check
github_checks:
  # https://docs.codecov.com/docs/common-recipe-list#disable-github-check-run-annotations
  annotations: false
