coverage:
  status:
    project:
      default:
        target: 95%    # the required coverage value: stop codecov.io from failing the build
        threshold: 1%  # allows a 50% drop from the previous base commit coverage
