
# A vscode remote container docker image with conda from
# https://hub.docker.com/_/microsoft-vscode-devcontainers

# A vscode remote container docker image with conda from
# https://hub.docker.com/_/microsoft-vscode-devcontainers
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
