name: black

on: [push, pull_request]

# use workaround due to: https://github.com/psf/black/issues/2079#issuecomment-812359146
jobs:
    check-formatting:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install Black
              run: pip install 'black==20.8b1' 'click==8.0.1'
            - name: Run black --check .
              run: black --check .
