name: ARMI Non-Linux Tests

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [windows-2022, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: Run Unit Tests
        run: |
          pip install -e .[memprof,mpi,test]
          pytest -n 4 armi
      - name: Find Test Crumbs
        run: python .github/workflows/find_test_crumbs.py
