name: PR Docs

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Building and deploying docs is broken on forked repos
    if: github.repository == 'terrapower/armi'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
      - name: Update package index
        run: sudo apt-get update
      - name: Install mpi libs
        run: sudo apt-get -y install libopenmpi-dev
      - name: Install Pandoc
        run: sudo apt-get -y install pandoc
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2.0.2
      - name: Make HTML Docs
        run: |
          pip install -e .[memprof,mpi,test,docs]
          cd doc
          git submodule init
          git submodule update
          make html
      - name: Archive Docs from PR
        uses: actions/upload-artifact@v4
        with:
          name: pr-docs
          path: doc/_build/html
          retention-days: 5
