name: Documentation

on:
  push:
    branches:
      - master
      - upgrade_sphinx

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Update package index
        run: sudo apt-get update
      - name: Install mpi libs
        run: sudo apt-get -y install libopenmpi-dev
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Make HTML Docs
        run: tox -e doc
